### ISSUE TITLE
Issue when trying to download fork for darknet weight export

### ISSUE THREAD

**Issue by pladosz** [ceccocats/tkDNN#198]
Hi,

When I try to download repository necessary to export weights from darknet [https://git.hipert.unimore.it/fgatti/darknet.git], I get error:

> fatal: unable to access 'https://git.hipert.unimore.it/fgatti/darknet.git/': Failed to connect to git.hipert.unimore.it port 443: Operation timed out

Could you please advise?

Thanks!

**Comment by rickymedrano** [comment]
I just tested it and this works
`git clone https://git.hipert.unimore.it/fgatti/darknet.git`

**Comment by pladosz** [comment]
Hi,

I just checked with internet tethered from my phone and indeed it works. Could it be that my university network blocks this specific port?

**Comment by rickymedrano** [comment]
> Hi,
> 
> I just checked with internet tethered from my phone and indeed it works. Could it be that my university network blocks this specific port?

No idea, that's on your end and you would need to investigate it. It could be your university network blocking certain sites or the hipert.unimore.it site that was temporarily down.

**Comment by mive93** [comment]
Hi @pladosz, 

yeah, we had problems with the university gitlab. Now it should be fixed.
Thanks @rickymedrano for the quick suppport.

**Comment by pladosz** [comment]
Thanks for all the help and replies. I think there is an issue with network settings on our end, as I still can't access it from my university network. I think this can be closed now?
